### ISSUE TITLE
umm_malloc version

### ISSUE THREAD

**Issue by sshahaev** [rhempel/umm_malloc#4]
Hello rhempel,

Thanks for the umm_malloc library. Could you please add version numbers for it?

Thanks

**Comment by rhempel** [comment]
Would you like that to be a `#define UMM_MALLOC_VERSION_MAJ/MIN/INC` or an API call that returns the version or ...

If you can provide a suggestion that works for you I'll be happy to look at it. I'd prefer to use semantic versioning so that we're clear on bugfix vs breaking change.

Finally, please let me know where you are using `umm_malloc` - I am always interested to know where it's being used :-)

**Comment by sshahaev** [comment]
I really don't need an API to get version or defines. In my opinion you could just use git tags to set version for specific library snapshot. Or you could use github capability to create releases:
https://help.github.com/articles/creating-releases/
https://help.github.com/articles/working-with-tags/

I'm using umm_malloc for IoT client on embedded devices like k64-f.

**Comment by rhempel** [comment]
I just created a v1.0.0 release after a major source reorganization - no change to functionality
