### ISSUE TITLE
Couple improvements

### ISSUE THREAD

**Issue by DouweVanNijnatten** [rhempel/umm_malloc#45]
Hi guys,

I noticed a couple of things in the master branch:

 - umm_info -> Compiler error -> line 165/171. Variable umm_metrics does not exist (I think it should be ummHeapInfo)
 - umm_integrity_check -> use of printf instead of DBGLOG_INFO functions
 - umm_poison -> get_unpoisoned()  wrong type of variable: uint8_t c must be uint16_t c

Best regards,
Douwe

**Comment by rhempel** [comment]
Thanks for the feedback! I am currently working on UMM-42 and have incorporated your suggestions:

- [ ] umm_info -> Compiler error -> line 165/171. Variable umm_metrics does not exist (I think it should be ummHeapInfo)
- [ ] umm_integrity_check -> use of printf instead of DBGLOG_INFO functions
- [ ] umm_poison -> get_unpoisoned() wrong type of variable: uint8_t c must be uint16_t c

**Comment by rhempel** [comment]
The above fixes will be in the next release when I finish UMM-42

**Comment by rhempel** [comment]
Finished UMM-42 and pushed to master - closing this issue - thanks for the input!
